env:
  - name: PROMETHEUS_TEST_URL
    value: "http://monitoring-kube-prometheus-prometheus:9090/metrics"
  - name: ALERTMANAGER_TEST_URL
    value: "http://monitoring-kube-prometheus-alertmanager:9093/metrics"
  - name: OPSGENIE_API_KEY
    value: "00000000-0000-0000-0000-000000000000"
  - name: PROJECT
    value: "my_project"
resources:
  requests:
    memory: "20Mi"
    cpu: "20m"
  limits:
    memory: "50Mi"
    cpu: "50m"
#affinity:
#  nodeAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      nodeSelectorTerms:
#      - matchExpressions:
#        - key: role
#          operator: In
#          values:
#          - infra
#tolerations:
#  - key: "application"
#    operator: "Exists"
#    effect: "NoSchedule"
