env:
  - name: PROMETHEUS_TEST_URL
    value: "http://kube-prometheus-stack-prometheus:9090/metrics"
  - name: ALERTMANAGER_TEST_URL
    value: "http://kube-prometheus-stack-alertmanager:9093/metrics"
  - name: OPSGENIE_API_KEY
    value: "/secrets/opsgenie-api-key" # path to mounted secret (see example secret in examples/helmfile/example-secret.yaml)
  - name: PROJECT
    value: "my_project" # this value added to template and resultimg heartbeat name will be: monitoring_my_project_prometheus
opsgenie_api_key:
  secret_name: "alertmanager-opsgenie-api-key" # secret name in the same namespace
  mount_path: "/secrets" # directory, where secret will be mounted
resources:
  requests:
    memory: "20Mi"
    cpu: "20m"
  limits:
    memory: "50Mi"
    cpu: "50m"
#affinity:
#  nodeAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      nodeSelectorTerms:
#      - matchExpressions:
#        - key: role
#          operator: In
#          values:
#          - infra
#tolerations:
#  - key: "application"
#    operator: "Exists"
#    effect: "NoSchedule"
