apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsgenie-heartbeat
  labels:
    app: opsgenie-heartbeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opsgenie-heartbeat
  template:
    metadata:
      labels:
        app: opsgenie-heartbeat
      annotations:
        monitoring: "true"
    spec:
      containers:
      - name: opsgenie-heartbeat
        image: shalb/opsgenie-heartbeat:0.0.1
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: opsgenie-api-key
          mountPath: "{{ .Values.opsgenie_api_key.mount_path }}"
          readOnly: true
        resources:
        {{- with .Values.resources }}
{{ toYaml . | indent 10 }}
        {{- end }}
        env:
        {{- with .Values.env }}
{{ toYaml . | indent 10 }}
        {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
      - name: opsgenie-api-key
        secret:
          secretName: {{ .Values.opsgenie_api_key.secret_name }}
